name: Heroku Deploy

on:
  workflow_run:
    workflows: ['Flask CI']
    branches: [master]
    types: [completed]

jobs:
  on-sucess:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Heroku Action
        # You may pin to the exact commit or the version.
        # uses: CDNievas/heroku-action@c9cf9c85571e67583e44ec92c0d1113f66b0e838
        uses: CDNievas/heroku-action@v1.0
        with:
          # Used for authentication. You can find it in your heroku homepage account settings
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          # Email from Heroku Account
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          # The appname to use for deploying/updating
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          # The branch that you would like to deploy to Heroku
          branch: main # optional, default is HEAD
          # Set this to true if want to use --force
          useforce: false # optional
          # Contents of the Procfile to save and deploy
          procfile: ./Procfile # optional, default is
